// Source: British Woodworking Federation, "Design Guide: Timber Stairs" (BWF Stair Scheme,
// produced for JELD-WEN (UK) Ltd, © 2013/2014), cross-referencing UK Building Regulations
// (Approved Document K 2013 — England; Technical Handbook — Scotland; Technical Booklet H —
// Northern Ireland; Approved Document K 1998+amendments — Wales) and BS/EN standards it cites.
//
// Two DIFFERENT kinds of rule live in this one file, and each entry says which:
//   - ruleType LEGAL_REQUIREMENT, jurisdiction UK  -> binding UK Building Regulations content,
//     reproduced here ONLY as comparative/reference material. These are NOT binding for a
//     project built to Polish jurisdiction and must never be evaluated unless the user
//     explicitly selects a UK legal profile.
//   - ruleType INDUSTRY_BEST_PRACTICE / ENGINEERING_GUIDANCE, jurisdiction UK -> BWF's own
//     trade-body recommendations and prescriptive joinery/material tables. These are useful,
//     transferable engineering practice even outside the UK, but are guidance, not law,
//     anywhere.
//
// No proprietary/reverse-engineered CAD or CAM logic is recorded here — only the publicly
// published figures from the cited guide and regulations.

import { defineRuleSet } from '../schema.js';

export const bwfIndustryGuidance = defineRuleSet([
  // --- A. Geometric (UK legal, reference only) ---
  {
    ruleId: 'UK-LEGAL-A-01',
    category: 'A',
    description: 'Overall relationship between rise (R) and going (G) for a private stair flight.',
    condition: '42 deg maximum pitch; 550 mm <= 2R + G <= 700 mm; tread breadth (nosing to back edge) must not be less than going',
    configRefs: ['riserHeight', 'treadGoing'],
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'UK',
    source: 'Approved Document K 2013 (England), §1.1-1.2, as summarised in BWF Timber Stair Design Guide 2013 §7.1',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Reference only — not binding for PL-jurisdiction projects. Compare with PL-LEGAL-A-01 (0.6-0.65m, narrower band) and note England permits R 150-220mm / G 220-300mm specifically, a wider design space than the Polish formula alone implies.',
  },
  {
    ruleId: 'UK-LEGAL-D-01',
    category: 'D',
    description: 'Minimum headroom above the pitch line of a standard stair flight.',
    condition: 'headroom >= 2.0 m',
    configRefs: ['minHeadroom'],
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'UK',
    source: 'Approved Document K 2013, Diagram 1.3, as reproduced in BWF Timber Stair Design Guide 2013 §7.2',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Reference only. Matches the project\'s current default (config.minHeadroom = 2000mm) — but see PL-LEGAL-D-01 which suggests the actual Polish figure may be 2.05m, still unverified.',
  },
  {
    ruleId: 'UK-LEGAL-D-02',
    category: 'D',
    description: 'Reduced headroom permitted specifically for loft-conversion stairs where 2.0m cannot be achieved.',
    condition: '1.8 m at centre-line, rising to 1.9 m at the side (measured per Diagram 1.4)',
    configRefs: [],
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'UK',
    source: 'Approved Document K 2013, Diagram 1.4, as reproduced in BWF Timber Stair Design Guide 2013 §7.2',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Reference only — illustrates that headroom minimums are context-dependent (a general "reduced headroom" concept the project could offer as an explicit, user-selected mode rather than a single hard-coded threshold).',
  },
  {
    ruleId: 'UK-LEGAL-C-01',
    category: 'C',
    description: 'Consecutive tapered (winder) treads must have the same going measured on the walk line; if a flight mixes straight and tapered treads, the tapered going must not be less than the straight going.',
    condition: 'going(winder_i) == going(winder_j) for all i,j in the same turn; going(winder) >= going(straight)',
    configRefs: ['treadGoing', 'windersPerTurn'],
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'UK',
    source: 'Approved Document K 2013 §1.3 / Diagram 1.9, as reproduced in BWF Timber Stair Design Guide 2013 §7.6 (England, Northern Ireland)',
    severity: 'INFO',
    blocksGeneration: false,
    notes:
      'Directly relevant to the project\'s proportional winder method: the current planLayout.js already keeps treadGoing constant along the walkline by construction, so it is compatible with this rule in spirit — but there is no explicit validation confirming the *as-built* winder going (after any manual edge override) still satisfies it.',
  },
  {
    ruleId: 'UK-GUID-C-02',
    category: 'C',
    description: 'Supplementary winder-flight construction parameters used to define and measure the walk line and tapered-tread geometry.',
    condition:
      'clear flight width measured between strings; walk line = arc centred on the newel (or string intersection), tangent to the centreline of the narrowest adjoining straight flight; ' +
      'max change of direction through one winder flight = 180 deg; narrowest tread width (nosing to nosing) >= 50 mm; ' +
      'max clear width for a winder flight to use this simplified method = 1000 mm',
    configRefs: ['walklineOffset', 'stairWidth', 'windersPerTurn'],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §7.6 "Supplementary information for winders" (items 1-8)',
    severity: 'INFO',
    blocksGeneration: false,
    notes:
      'This is the clearest, most implementation-relevant external description of "how to define a walkline" available from a non-proprietary source. It differs from the project\'s current walklineOffset/walklineSplitOffset model (which is a proportional-interpolation method, not an arc-around-newel method) — worth comparing directly when redesigning the winder solver (see prior geometry audit, problem C.4).',
  },
  {
    ruleId: 'US-REF-C-03',
    category: 'C',
    description:
      'Comparative reference only (International Residential Code, US — a different jurisdiction, not applied by default): walkline fixed at 305 mm (12in) from the narrow side of a winder; consistency tolerance of 9.5 mm (3/8in) between the widest and narrowest winder going within a flight.',
    condition: 'walklineOffsetFromNarrowSide = 305 mm; max(going) - min(going) <= 9.5 mm within one flight',
    configRefs: [],
    ruleType: 'ENGINEERING_GUIDANCE',
    jurisdiction: 'US',
    source: '2021 International Residential Code, §R311.7.5.2 (as summarised by up.codes and multiple US building-code explainer sources)',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Included purely as a cross-jurisdiction comparison point for the walkline concept — has no legal standing in PL or UK contexts and should never be silently enabled.',
  },

  // --- E. Construction / material rules ---
  {
    ruleId: 'BWF-GUID-E-01',
    category: 'E',
    description: 'Indicative target moisture-content ranges for stair timber, by service environment.',
    condition: 'internal, heated: MC 7%-11% (~50% RH) | internal, unheated: MC 10%-14% (~65% RH)',
    configRefs: [],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013, Table 3.1',
    severity: 'INFO',
    blocksGeneration: false,
  },
  {
    ruleId: 'BWF-GUID-E-02',
    category: 'E',
    description: 'Reference list of timber species commonly accepted for staircases, with their assigned EN 1912 strength class (informational — not exhaustive; any species/grade choice should be verified by calculation or test if not listed).',
    condition: 'e.g. European redwood/whitewood/oak/larch -> C24; beech/sapele/American red oak -> D40; American white oak -> D50',
    configRefs: [],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013, Table 4.1 (values per BS EN 1912:2012)',
    severity: 'INFO',
    blocksGeneration: false,
  },
  {
    ruleId: 'BWF-GUID-E-03',
    category: 'E',
    description: 'Minimum adhesive performance class for internal structural glued joints.',
    condition: 'adhesiveClass >= D3 (BS EN 204) or C1 (BS EN 12765)',
    configRefs: [],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §4.4',
    severity: 'INFO',
    blocksGeneration: false,
  },
  {
    ruleId: 'BWF-GUID-E-04',
    category: 'E',
    description: 'Minimum corrosion-resistance class for metal fasteners/fittings, by environment.',
    condition: 'heated interior: neutral salt-spray Class 2 (BS EN 1670 minimum) | unheated interior: Class 3',
    configRefs: [],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §4.5.2',
    severity: 'INFO',
    blocksGeneration: false,
  },

  // --- F. Stringer / stringboard ---
  {
    ruleId: 'BWF-GUID-F-01',
    category: 'F',
    description: 'Strings should be housed to receive treads and risers to a minimum depth, with a tapered wedge-and-glue joint for rigidity (unless an alternative side-restraint system replaces the wedges for aesthetic reasons).',
    condition: 'housingDepth >= max(12 mm, 0.4 * stringerThickness)',
    configRefs: ['stringerThickness'],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §6.2.3',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Describes the "closed string" (housed) construction method as distinct from a "cut string" (open, notched) — the current project models neither explicitly; stringerGeometry.js only produces flat cut-outer-face panels with no housing concept.',
  },
  {
    ruleId: 'BWF-GUID-F-02',
    category: 'F',
    description: 'Where a string terminates in a newel, its end should be formed as a tenon fitting into a newel mortice.',
    condition: 'tenonThickness >= 12 mm; tenonLength >= 45 mm (may be reduced/haunched where two strings share one newel)',
    configRefs: ['postSize'],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §6.2.3',
    severity: 'INFO',
    blocksGeneration: false,
  },
  {
    ruleId: 'BWF-GUID-F-03',
    category: 'F',
    description: 'Upper and lower strings at a winder turn may need local enlargement to accommodate the housings of the winder treads.',
    condition: 'stringWidthAtTurn >= stringWidthElsewhere (enlarged as needed by winder housing geometry)',
    configRefs: [],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §6.2.3',
    severity: 'WARNING',
    blocksGeneration: false,
    notes:
      'Directly relevant to the geometry-audit finding that the current winder stringer generation is a documented source of instability (computeNormal() heuristics in stringerGeometry.js) — this rule confirms the *general* industry expectation is that winder strings are treated as a distinct, purpose-shaped construction problem, not the same flat-panel logic as a straight flight.',
  },
  {
    ruleId: 'BWF-GUID-F-04',
    category: 'F',
    description: 'Prescriptive minimum string cross-section for a standard domestic stair within a stated envelope (max. 900mm overall width, 13 full risers/treads, treads let into strings).',
    condition: 'stringSection >= 220 mm x 26 mm (valid ONLY within the stated envelope — see notes)',
    configRefs: ['stringerHeight', 'stringerThickness'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013, Table 6.1',
    severity: 'INFO',
    blocksGeneration: false,
    notes:
      'Classified as MANUFACTURING_ASSUMPTION (not INDUSTRY_BEST_PRACTICE) here because it is only valid inside the explicit envelope the guide states (<=900mm width, 13 risers). Applying this number outside that envelope, or to a self-supporting stringer design of the kind this project targets, requires recalculation per EC5-STRUCT-F-01/EC5-STRUCT-I-01, not a copy of this figure.',
  },

  // --- G. Tread/riser construction ---
  {
    ruleId: 'BWF-GUID-G-01',
    category: 'G',
    description: 'Risers should be screw-fixed to the edge of the lower tread at defined centres, with a minimum screw penetration.',
    condition: 'screwCentres <= 230 mm; penetration >= max(23 mm, 1.5 * riserThickness)',
    configRefs: ['riserBoardThickness'],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §6.2.2',
    severity: 'INFO',
    blocksGeneration: false,
  },
  {
    ruleId: 'BWF-GUID-G-02',
    category: 'G',
    description: 'The riser top should locate into a groove in the underside of the tread, within a stated depth range, reinforced by glued angle blocks whose count scales with stair width.',
    condition: 'grooveDepth: 5 mm <= depth <= 0.25 * treadThickness; angleBlocks: 2 (width<=900mm) | 3 (900-990mm) | 4 (990-1200mm, or tapered treads >1200mm long)',
    configRefs: ['treadThickness', 'stairWidth'],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §6.2.2',
    severity: 'INFO',
    blocksGeneration: false,
  },
  {
    ruleId: 'UK-LEGAL-G-03',
    category: 'G',
    description: 'Where a stair has open risers, consecutive treads must overlap and the resulting gap must not admit a 100mm test sphere (child-safety requirement).',
    condition: 'treadOverlap >= 16 mm (England/NI/Wales) | >= 15 mm (Scotland); openingSize < 100 mm sphere',
    configRefs: ['nosing', 'hasRiserBoards'],
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'UK',
    source: 'Approved Document K 2013 §1.9, as reproduced in BWF Timber Stair Design Guide 2013 §7.9',
    severity: 'INFO',
    blocksGeneration: false,
    notes:
      'Reference only for PL projects, but directly actionable: the project already has config.hasRiserBoards=false (open-riser) as a real, user-selectable mode — this is exactly the rule that should validate that mode once a validation layer exists. Polish equivalent wording for open-riser child safety was not located during this research pass and should be checked separately (candidate gap — flag for follow-up research, not to be assumed absent).',
  },
  {
    ruleId: 'BWF-GUID-G-04',
    category: 'G',
    description: 'No externally-sourced prescriptive rule was found for winder-riser (splayed/fan-shaped riser board) construction — this is an open engineering question requiring first-principles derivation, not a documented industry number.',
    condition: 'n/a — no numeric condition available from public sources reviewed',
    configRefs: [],
    ruleType: 'ENGINEERING_GUIDANCE',
    jurisdiction: 'GENERAL',
    source: 'Absence noted after reviewing BWF Timber Stair Design Guide 2013, Approved Document K 2013, and Polish Warunki Techniczne §66-71 — none address winder riser board shape/construction explicitly',
    severity: 'INFO',
    blocksGeneration: false,
    notes:
      'Directly maps to problem C.3 from the prior geometry audit (flat single-panel winder riser gives unnatural geometry). This gap must be closed by engineering judgement/first-principles design (e.g. segmented or kite-shaped riser), not by searching harder for an external number — record any design decision made here as a new rule in manufacturingAssumptions.js or a project-specific rule set, not as if it were an external standard.',
  },

  // --- B. Ergonomic (component sizes as evidence of comfortable/safe scale) ---
  {
    ruleId: 'BWF-GUID-B-01',
    category: 'B',
    description: 'Minimum handrail-height band and requirement for a handrail once a flight exceeds a minimum total rise.',
    condition: 'handrailRequired if totalRise > 0.6 m; handrailHeight in [0.9 m, 1.1 m] above pitch line (England/NI); both sides required if stairWidth >= 1.0 m',
    configRefs: ['stairWidth'],
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'UK',
    source: 'Approved Document K 2013 §1.5, as reproduced in BWF Timber Stair Design Guide 2013 §6.2.5/§7.5',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Reference only for PL projects — Polish handrail-height rule is captured separately as PL-LEGAL-H-01 (balustrade height, a different clause).',
  },
  {
    ruleId: 'BWF-GUID-B-02',
    category: 'B',
    description: 'Minimum baluster/newel/handrail cross-sections for a standard domestic stair (900mm high balusters).',
    condition: 'newel >= 82x82 mm; handrail >= 68x45 mm; baluster >= 27mm square or 35mm turned at narrowest point',
    configRefs: ['postSize'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013, Table 6.1',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Project default config.postSize = 110mm already exceeds this minimum comfortably.',
  },

  // --- I. Structural loading (UK National Annex values, reference only) ---
  {
    ruleId: 'UK-GUID-I-01',
    category: 'I',
    description: 'Imposed loading for stair strings, treads and landings in domestic occupancy (Category A1) per the UK National Annex to EN 1991-1-1.',
    condition: 'UDL = 1.5 kN/m^2 ; concentrated load = 2.0 kN (applied at the most onerous position)',
    configRefs: [],
    ruleType: 'ENGINEERING_GUIDANCE',
    jurisdiction: 'UK',
    source: 'UK National Annex to BS EN 1991-1-1, Table NA.3, as reproduced in BWF Timber Stair Design Guide 2013, Table 5.1',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Reference only — do not assume this equals the Polish national-annex value; see PL-LEGAL-I-01 (unverified, flagged separately).',
  },
  {
    ruleId: 'UK-GUID-I-02',
    category: 'I',
    description: 'Horizontal loading for handrails and balustrade infill panels, domestic occupancy (Category A1).',
    condition: 'handrail UDL = 0.36 kN/m ; infill UDL = 0.5 kN/m^2 ; infill concentrated load = 0.35 kN ; handrail deflection <= 25 mm (or must resist 2.5x load in a single test without failure)',
    configRefs: [],
    ruleType: 'ENGINEERING_GUIDANCE',
    jurisdiction: 'UK',
    source: 'UK National Annex Table NA.8 / PD 6688-1-1:2011 Table 2, as reproduced in BWF Timber Stair Design Guide 2013, Table 5.2',
    severity: 'INFO',
    blocksGeneration: false,
  },
  {
    ruleId: 'BWF-GUID-I-03',
    category: 'I',
    description: 'Timber is a Category E reaction-to-fire product by default (no fire performance required for stairs within a single dwelling); a stair providing compartmentation between two fire compartments needs a fire-resistant covering (typically plasterboard) to its underside.',
    condition: 'fireResistanceRequired = (stair separates two fire compartments)',
    configRefs: [],
    ruleType: 'ENGINEERING_GUIDANCE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §3.6, citing BS EN 13501-1 and BS EN 1365-6',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Out of scope for the current geometry model but relevant to any future "compliance report" feature.',
  },
]);
