// Manufacturing constraints and company-defined defaults. These rules have NO external
// standard to cite — they exist because a real workshop has real stock sizes, tooling,
// and pricing, none of which are determined by law or by general engineering principle.
//
// Every rule here is ruleType MANUFACTURING_ASSUMPTION or USER_DEFINED_COMPANY_STANDARD,
// jurisdiction COMPANY. They MUST remain trivially editable per company/workshop — never
// hard-code them as if they were physical law. Numeric values below are placeholders
// mirroring the project's current config.js defaults, not researched industry norms —
// each should be confirmed or overridden by the actual company using the tool.

import { defineRuleSet } from '../schema.js';

export const manufacturingAssumptions = defineRuleSet([
  {
    ruleId: 'CO-MFG-J-01',
    category: 'J',
    description: 'Standard stock thickness increments available for treads and risers (workshop-specific — depends on supplier and planer/thicknesser setup).',
    condition: 'treadThickness in {e.g. 32, 40, 45} mm; riserBoardThickness in {e.g. 18, 20, 22} mm (placeholder set — replace with actual stock list)',
    configRefs: ['treadThickness', 'riserBoardThickness'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No external source — placeholder mirroring current config.js defaults (treadThickness: 40mm, riserBoardThickness: 20mm)',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'This should become a company-editable list (not a fixed enum) once the rules layer is wired into a UI — the point of this rule is to make explicit that "40mm" in schema.js is a company choice, not a technical requirement.',
  },
  {
    ruleId: 'CO-MFG-J-02',
    category: 'J',
    description: 'Maximum practical single-piece stringer/tread length limited by available raw board stock and machinery bed length.',
    condition: 'componentLength <= maxStockLength (workshop-specific, e.g. 3000-4000 mm) — otherwise requires a scarf/finger joint, itself a separate manufacturing decision',
    configRefs: [],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No external source — placeholder pending real workshop data',
    severity: 'WARNING',
    blocksGeneration: false,
    notes: 'Relevant to long, shallow-pitch stringers in wide/long straight flights — currently nothing in the project checks stringer length against any stock limit.',
  },
  {
    ruleId: 'CO-MFG-J-03',
    category: 'J',
    description: 'Housed/wedged string joints require a tapered housing with wedge clearance — a manufacturing (tooling/CNC path) constraint distinct from the structural joint principle itself (see BWF-GUID-F-01).',
    condition: 'housingTaperAllowance > 0 (tool/process-specific)',
    configRefs: [],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No external numeric source — derived from the general joinery principle in BWF Timber Stair Design Guide 2013 §6.2.3',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Out of scope for the current 3D model (no CAM/toolpath layer exists), recorded here so it is not forgotten once stringer housings are modelled explicitly.',
  },
  {
    ruleId: 'CO-MFG-J-04',
    category: 'J',
    description: 'Minimum practical width for a solid-timber winder tread at its narrow point, for production feasibility (distinct from the legal ergonomic minimum in PL-LEGAL-C-01 or the UK guidance figure in UK-GUID-C-02) — very narrow points are structurally weak and hard to machine/finish cleanly regardless of what the law permits.',
    condition: 'winderTreadWidthAtNarrowPoint >= companyMinimum (placeholder: 80-100 mm, stricter than the 50mm UK guidance figure and the 250mm-at-0.4m PL legal figure — confirm against actual shop practice)',
    configRefs: ['minInnerWidth'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No external source — placeholder; project\'s current config.minInnerWidth default is 110mm',
    severity: 'WARNING',
    blocksGeneration: false,
  },
  {
    ruleId: 'CO-STD-J-05',
    category: 'J',
    description: 'Material waste/kerf allowance applied when converting a material takeoff (lengths/areas) into a cost estimate.',
    condition: 'estimatedCost = materialQuantity * (1 + wasteFactor) * unitPrice ; wasteFactor is company-editable, default 0%',
    configRefs: [],
    ruleType: 'USER_DEFINED_COMPANY_STANDARD',
    jurisdiction: 'COMPANY',
    source: 'No external source — required placeholder for business goal 3 ("orientacyjny koszt materiału"); does not exist anywhere in the current codebase',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'This rule exists to mark that cost estimation needs an explicit, editable waste-factor policy — it should never be a hidden constant inside a cost function (RULES.md rule 11).',
  },
  {
    ruleId: 'CO-STD-E-01',
    category: 'E',
    description: 'Default stringer height (structural depth below the step line) and thickness, as a starting point for a self-supporting timber stringer — not derived from any cited structural calculation, pending EC5-STRUCT-I-01/I-02 being wired to real timber grade data.',
    condition: 'stringerHeight = 300 mm (default) ; stringerThickness = 40 mm (default)',
    configRefs: ['stringerHeight', 'stringerThickness'],
    ruleType: 'USER_DEFINED_COMPANY_STANDARD',
    jurisdiction: 'COMPANY',
    source: 'No external source — mirrors current config.js defaults, presented explicitly as a company standard pending a real structural check',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'This is the single most important rule to eventually REPLACE with a real EC5 calculation (per EC5-STRUCT-I-01) rather than keep as a fixed default once span/load/grade become real inputs.',
  },
  {
    ruleId: 'CO-STD-B-01',
    category: 'B',
    description:
      'Company-preferred riser-height range for standard residential production — narrower than both the Polish legal maximum and the general "comfortable" industry range, reflecting this workshop\'s own house style/stock (e.g. a fixed family of stringer housing jigs cut for a specific riser band).',
    condition: '150 mm <= riserHeight <= 180 mm (placeholder — replace with the actual company policy)',
    configRefs: ['riserHeight'],
    scope: { locations: ['internal'] },
    ruleType: 'USER_DEFINED_COMPANY_STANDARD',
    jurisdiction: 'COMPANY',
    source: 'No external source — company policy placeholder, freely editable per workshop',
    severity: 'WARNING',
    blocksGeneration: false,
    notes:
      'This is the third of the four layers in the profile-system worked example (see docs/rules/PROFILES.md): PL-LEGAL-A-05a sets the legal ceiling (190mm), GEN-ERGO-B-05 sets a comfort band (170-190mm), THIS rule narrows it further to this company\'s preferred range (150-180mm), and USER-PREF-B-01 (userDesignPreferences.js) can narrow it once more for one specific project/client. A value can satisfy the law and general comfort guidance while still failing this company\'s own narrower standard — that is the point of keeping it a separate, independently-editable rule.',
  },
  {
    ruleId: 'CO-STD-G-01',
    category: 'G',
    description: 'Default nosing projection.',
    condition: 'nosing = 25 mm (default)',
    configRefs: ['nosing'],
    ruleType: 'USER_DEFINED_COMPANY_STANDARD',
    jurisdiction: 'COMPANY',
    source: 'No external numeric source found — 20-25mm is common informal practice but was not confirmed in any of the primary sources reviewed (PL Warunki Techniczne, BWF Guide, UK Building Regs)',
    severity: 'INFO',
    blocksGeneration: false,
  },
]);
