// Manufacturing constraints and company-defined defaults. These rules have NO external
// standard to cite — they exist because a real workshop has real stock sizes, tooling,
// and pricing, none of which are determined by law or by general engineering principle.
//
// Every rule here is ruleType MANUFACTURING_ASSUMPTION or USER_DEFINED_COMPANY_STANDARD,
// jurisdiction COMPANY. They MUST remain trivially editable per company/workshop — never
// hard-code them as if they were physical law. Numeric values below are placeholders
// mirroring the project's current config.js defaults, not researched industry norms —
// each should be confirmed or overridden by the actual company using the tool.

import { defineRuleSet } from '../schema.js';

export const manufacturingAssumptions = defineRuleSet([
  {
    ruleId: 'CO-MFG-J-POST-TREAD-HOUSING',
    category: 'J',
    description: 'A tread that passes through a structural post (the first/last tread at a newel, the winder treads at a corner post) gets ONE plain notch round the post and enters it with ONE tongue — on the face it bears on most, across its full width there — milling the tread end as little as possible for the largest support (user rule 2026-09-28). A riser carries no load: it is only cut flush with the post, no pocket.',
    condition: 'tread outline minus (post square without the chosen face band, postTreadHousingDepthMm deep); one pocket = the tongue width x the tread thickness x that depth; risers: outline minus the post square',
    configRefs: ['postTreadHousingDepthMm'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'Joint stage 2 of the user-chosen joint plan (2026-09-28). No source for the 20 mm default — placeholder mirroring stringerHousingDepthMm; BWF-GUID-F-01 (housing depth >= max(12 mm, 0.4 x string thickness)) concerns tread housings in a string, not in a newel.',
    severity: 'INFO',
    blocksGeneration: false,
    needsVerification: true,
  },
  {
    ruleId: 'CO-MFG-J-POST-HOUSING',
    category: 'J',
    description: 'A stringer meets a structural post (newel, corner post) by entering, with its FULL cross-section, a pocket (wreg) milled into the post face; the post DXF shows the pocket, the stringer is lengthened by its depth.',
    condition: 'pocket depth = postHousingDepthMm (0 = stringer butts against the post face); pocket = the stringer section over the depth, clipped to the post',
    configRefs: ['postHousingDepthMm'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'Joint type chosen by the user (2026-09-28). No source for the 20 mm default — placeholder mirroring stringerHousingDepthMm. For comparison, BWF-GUID-F-02 (BWF Guide §6.2.3) describes a TENON joint instead: tenon >= 12 mm thick, >= 45 mm long.',
    severity: 'INFO',
    blocksGeneration: false,
    needsVerification: true,
    notes: 'Connectors (stair bolts / dowels) through this joint are a separate, later stage.',
  },
  {
    ruleId: 'CO-MFG-J-CONNECTORS',
    category: 'J',
    description: 'Stringer joints (stringer into a post housing, stringer butting into another stringer) are bolted: a stair bolt along the joint axis — through the post (or blind into it) / through the board butted into — into the end of the stringer, up to a nut-access bore in its inner face. Holes are drawn in the stringer and post DXFs; the bolts are listed unpriced in the takeoff.',
    condition: 'jointConnectorCount bolts per joint, jointConnectorSpacingMm apart (vertical, centred on the stringer section at the joint face), diameter jointConnectorDiameterMm, jointConnectorBoardDepthMm into the stringer, nut bore jointConnectorNutBoreMm; post mode through / blind (jointConnectorPostDepthMm). Edge distance >= 3d (EN 1995-1-1 Table 8.4, a4,c for bolts — to verify); a post keeping < 50 % of its section at some height is reported (judgement threshold).',
    configRefs: ['jointConnectorCount', 'jointConnectorSpacingMm', 'jointConnectorDiameterMm', 'jointConnectorBoardDepthMm', 'jointConnectorNutBoreMm', 'jointConnectorPostMode', 'jointConnectorPostDepthMm'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'Joint stage 4 of the user-chosen joint plan (2026-09-28: connectors as parameters). No source for any default (2 x M10, 120 mm, 100 mm, O30, through the post) — placeholders to be confirmed by the workshop / the bolt manufacturer.',
    severity: 'INFO',
    blocksGeneration: false,
    needsVerification: true,
  },
  {
    ruleId: 'CO-MFG-J-CANTILEVER',
    category: 'J',
    description: 'Cantilever stair: steel profiles (about 40 x 60, full section) stick out of the wall, the company finds them on site; every tread is a wooden cladding box slid onto its profiles (glued or screwed) — top and front 40 mm, bottom, back and the free-end side 20 mm; the top is full (with the nosing), the front under the top, the bottom between the front and the back, the back under the top, the side between the top and the bottom; the wall end is open; at least 2 profiles per tread; the side away from the wall is free; winder treads get the same box in their own shape; a box at most about 1800 mm wide.',
    condition: 'stairConstruction = cantilever; box height = profile height + clearance + top + bottom; cantileverProfileCount >= 2; stairWidth - wall gap <= cantileverMaxWidthMm',
    configRefs: ['stairConstruction', 'cantileverProfileWidthMm', 'cantileverProfileHeightMm', 'cantileverProfileCount', 'cantileverProfileProjectionMm', 'cantileverClearanceMm', 'cantileverTopThicknessMm', 'cantileverFrontThicknessMm', 'cantileverShellThicknessMm', 'cantileverWallGapMm', 'cantileverMaxWidthMm'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'Construction described by the user (2026-09-29): profile 40 x 60, 2+ per tread, 40/20 mm cladding and its assembly, box = profile + 40 + 20, max ~1800 mm. The slide-on clearance (2 mm), the wall gap (5 mm) and the profile projection (700 mm) are placeholders — the profiles are measured on site.',
    severity: 'INFO',
    blocksGeneration: false,
    needsVerification: true,
    notes: 'The steel (profiles, wall stringer) is not supplied by the company and is not checked; the cladding is priced from the board price list per board thickness.',
  },
  {
    ruleId: 'CO-MFG-J-GLASS',
    category: 'J',
    description: 'Glass balustrade: panes fixed to the side of the wanga on point fixings (rotule) with the handrail sitting on the glass, or hung between posts on rectangular clamps with the handrail on the posts; VSG 4.4.2 or 5.5.2, a pane at most 1800 mm wide; glass is flat, so every straight stretch of the path gets its own panes.',
    condition: 'railingInfill glass-side | glass-posts; railingGlassMaxWidthMm (1800, user decision); glass colour railingGlassTint (clear/optiwhite/graphite/bronze, user decision); rotule always Ø30 (user decision); between posts: a pane hangs post to post, clamps always on the post, only the gap to the handrail (railingGlassTopGapMm) and to the bottom (railingGlassBottomGapMm) are set, the glass-to-post-face distance comes from the clamp (GLASS_TO_POST_MM 10 mm); on rotules: gap between panes railingGlassGapMm, stand-off railingGlassStandoffMm, overlap below the wanga top railingGlassOverlapMm — placeholders',
    configRefs: ['railingInfill', 'railingGlassType', 'railingGlassTint', 'railingGlassMaxWidthMm', 'railingGlassGapMm', 'railingGlassTopGapMm', 'railingGlassBottomGapMm', 'railingGlassStandoffMm', 'railingGlassOverlapMm', 'railingGlassFixingsPerPane', 'railingGlassClampsPerSide'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'Mounting types, glass types and the 1800 mm maximum: user decisions 2026-09-29. The gap (20 mm), stand-off (30 mm), overlap on the wanga (120 mm), 2 rotules per pane, 2 clamps per edge and the 150 mm fixing inset are placeholders — to be confirmed by the glass / fixing supplier. The glass itself (pane strength, fixing capacity) is not checked.',
    severity: 'INFO',
    blocksGeneration: false,
    needsVerification: true,
  },
  {
    ruleId: 'CO-MFG-J-TOP-NOSING',
    category: 'J',
    description: 'Stairs with risers end with a riser too: at the top, on the slab edge, a thinner "fajkowy" nosing tread is laid flush with the upper floor, and the last riser stands under it (from the underside of the last tread up to the underside of that nosing tread, plus the usual riser-into-tread overlap).',
    condition: 'hasRiserBoards => top riser: bottom = underside of the last tread, top = totalRise - topNosingThicknessMm + riserTopOverlapMm',
    configRefs: ['hasRiserBoards', 'topNosingThicknessMm', 'riserTopOverlapMm'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'Company practice as described by the user (2026-09-28); the 20 mm default thickness of the nosing tread is a placeholder — it must match the actual upper floor finish.',
    severity: 'INFO',
    blocksGeneration: false,
    needsVerification: true,
    notes: 'The fajkowy nosing tread itself is not modelled (it is fitted with the floor); only the top riser under it is drawn, priced and exported.',
  },
  {
    ruleId: 'CO-MFG-J-01',
    category: 'J',
    description: 'Standard stock thickness increments available for treads and risers (workshop-specific — depends on supplier and planer/thicknesser setup).',
    condition: 'treadThickness in {e.g. 32, 40, 45} mm; riserBoardThickness in {e.g. 18, 20, 22} mm (placeholder set — replace with actual stock list)',
    configRefs: ['treadThickness', 'riserBoardThickness'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No external source — placeholder mirroring current config.js defaults (treadThickness: 40mm, riserBoardThickness: 20mm)',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'This should become a company-editable list (not a fixed enum) once the rules layer is wired into a UI — the point of this rule is to make explicit that "40mm" in schema.js is a company choice, not a technical requirement.',
  },
  {
    ruleId: 'CO-MFG-J-02',
    category: 'J',
    description: 'Maximum practical single-piece stringer/tread length limited by available raw board stock and machinery bed length.',
    condition: 'componentLength <= maxStockLength (workshop-specific, e.g. 3000-4000 mm) — otherwise requires a scarf/finger joint, itself a separate manufacturing decision',
    configRefs: [],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No external source — placeholder pending real workshop data',
    severity: 'WARNING',
    blocksGeneration: false,
    notes: 'Relevant to long, shallow-pitch stringers in wide/long straight flights — currently nothing in the project checks stringer length against any stock limit.',
  },
  {
    ruleId: 'CO-MFG-J-03',
    category: 'J',
    description: 'Housed/wedged string joints require a tapered housing with wedge clearance — a manufacturing (tooling/CNC path) constraint distinct from the structural joint principle itself (see BWF-GUID-F-01).',
    condition: 'housingTaperAllowance > 0 (tool/process-specific)',
    configRefs: [],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No external numeric source — derived from the general joinery principle in BWF Timber Stair Design Guide 2013 §6.2.3',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'Out of scope for the current 3D model (no CAM/toolpath layer exists), recorded here so it is not forgotten once stringer housings are modelled explicitly.',
  },
  {
    ruleId: 'CO-MFG-J-04',
    category: 'J',
    description: 'Minimum practical width for a solid-timber winder tread at its narrow point, for production feasibility (distinct from the legal ergonomic minimum in PL-LEGAL-C-01 or the UK guidance figure in UK-GUID-C-02) — very narrow points are structurally weak and hard to machine/finish cleanly regardless of what the law permits.',
    condition: 'winderTreadWidthAtNarrowPoint >= companyMinimum (placeholder: 80-100 mm, stricter than the 50mm UK guidance figure and the 250mm-at-0.4m PL legal figure — confirm against actual shop practice)',
    configRefs: ['minInnerWidth'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No external source — placeholder; project\'s current config.minInnerWidth default is 110mm',
    severity: 'WARNING',
    blocksGeneration: false,
  },
  {
    ruleId: 'CO-STD-J-05',
    category: 'J',
    description: 'Material waste/kerf allowance applied when converting a material takeoff (lengths/areas) into a cost estimate.',
    condition: 'estimatedCost = materialQuantity * (1 + wasteFactor) * unitPrice ; wasteFactor is company-editable, default 0%',
    configRefs: [],
    ruleType: 'USER_DEFINED_COMPANY_STANDARD',
    jurisdiction: 'COMPANY',
    source: 'No external source — required placeholder for business goal 3 ("orientacyjny koszt materiału"); does not exist anywhere in the current codebase',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'This rule exists to mark that cost estimation needs an explicit, editable waste-factor policy — it should never be a hidden constant inside a cost function (RULES.md rule 11).',
  },
  {
    ruleId: 'CO-STD-E-01',
    category: 'E',
    description: 'Default minimum stringer depth (structural depth below the step line) and thickness, as a starting point for a self-supporting timber stringer — not derived from any cited structural calculation, pending EC5-STRUCT-I-01/I-02 being wired to real timber grade data.',
    condition: 'minimumStringerDepthMm = 350 mm (default) ; stringerThickness = 40 mm (default)',
    configRefs: ['minimumStringerDepthMm', 'stringerThickness'],
    ruleType: 'USER_DEFINED_COMPANY_STANDARD',
    jurisdiction: 'COMPANY',
    source: 'No external source — mirrors current config.js defaults, presented explicitly as a company standard pending a real structural check',
    severity: 'INFO',
    blocksGeneration: false,
    notes: 'This is the single most important rule to eventually REPLACE with a real EC5 calculation (per EC5-STRUCT-I-01) rather than keep as a fixed default once span/load/grade become real inputs.',
  },
  {
    ruleId: 'CO-STD-B-01',
    category: 'B',
    description:
      'Company-preferred riser-height range for standard residential production — narrower than both the Polish legal maximum and the general "comfortable" industry range, reflecting this workshop\'s own house style/stock (e.g. a fixed family of stringer housing jigs cut for a specific riser band).',
    condition: '150 mm <= riserHeight <= 180 mm (placeholder — replace with the actual company policy)',
    configRefs: ['riserHeight'],
    scope: { locations: ['internal'] },
    ruleType: 'USER_DEFINED_COMPANY_STANDARD',
    jurisdiction: 'COMPANY',
    source: 'No external source — company policy placeholder, freely editable per workshop',
    severity: 'WARNING',
    blocksGeneration: false,
    notes:
      'This is the third of the four layers in the profile-system worked example (see docs/rules/PROFILES.md): PL-LEGAL-A-05a sets the legal ceiling (190mm), GEN-ERGO-B-05 sets a comfort band (170-190mm), THIS rule narrows it further to this company\'s preferred range (150-180mm), and USER-PREF-B-01 (userDesignPreferences.js) can narrow it once more for one specific project/client. A value can satisfy the law and general comfort guidance while still failing this company\'s own narrower standard — that is the point of keeping it a separate, independently-editable rule.',
  },
  {
    ruleId: 'CO-STD-G-01',
    category: 'G',
    description: 'Default nosing projection.',
    condition: 'nosing = 25 mm (default)',
    configRefs: ['nosing'],
    ruleType: 'USER_DEFINED_COMPANY_STANDARD',
    jurisdiction: 'COMPANY',
    source: 'No external numeric source found — 20-25mm is common informal practice but was not confirmed in any of the primary sources reviewed (PL Warunki Techniczne, BWF Guide, UK Building Regs)',
    severity: 'INFO',
    blocksGeneration: false,
  },
]);
