// Polish binding law: Rozporządzenie Ministra Infrastruktury z dnia 12.04.2002 r. w sprawie
// warunków technicznych, jakim powinny odpowiadać budynki i ich usytuowanie (Dz.U. 2002 nr 75
// poz. 690, z późn. zm.), Dział III, Rozdział 4 "Schody i pochylnie" (§ 66-71), oraz Dział VII
// "Bezpieczeństwo użytkowania" § 298 (balustrady).
//
// EVERY rule in this file is ruleType LEGAL_REQUIREMENT, jurisdiction PL. Do not add
// engineering guidance or industry best-practice entries here — see src/rules/README.md
// for why legal and non-legal sources must never share a file.

import { defineRuleSet } from '../schema.js';

export const plWarunkiTechniczne = defineRuleSet([
  {
    ruleId: 'PL-LEGAL-A-01',
    category: 'A',
    description:
      'Wzór Blondela dla schodów stałych wewnętrznych: podwojona wysokość stopnia plus jego szerokość (głębokość) musi mieścić się w przedziale 0,6-0,65 m.',
    condition: '0.6 m <= 2*riserHeight + treadGoing <= 0.65 m',
    configRefs: ['riserHeight', 'treadGoing'],
    scope: { locations: ['internal'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 69 ust. 4',
    // Decyzja użytkownika (2026-09-25): wzór Blondela jest w programie TYLKO INFORMACYJNY — ostrzeżenie w Walidacji,
    // nigdy blokada kosztorysu ani czynnik wpływający na geometrię (patrz geometry/stairwellFit.js). Przepis jako
    // taki pozostaje wiążący (ruleType LEGAL_REQUIREMENT bez zmian) — to projektant decyduje, co z tym zrobić.
    severity: 'WARNING',
    blocksGeneration: false,
    notes:
      'Obniżone z ERROR do WARNING decyzją użytkownika: w programie tylko informacja, bez blokady kosztorysu. Próg 600-650 mm jest w config/schema.js jako BLONDEL_RANGE_MM (ta sama wartość).',
  },
  {
    ruleId: 'PL-LEGAL-A-02',
    category: 'A',
    description: 'Maksymalne nachylenie biegu schodów przeznaczonych do stałej komunikacji.',
    condition: 'stairPitchAngle <= 36 deg',
    configRefs: ['riserHeight', 'treadGoing'],
    scope: { locations: ['internal'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 69 (interpretacja: nachylenie wynikające z 2h+s)',
    severity: 'ERROR',
    blocksGeneration: true,
    notes: 'Kąt nachylenia nie jest osobnym niezależnym parametrem — wynika z riserHeight/treadGoing i jest w praktyce ograniczony już przez PL-LEGAL-A-01, ale bywa cytowany osobno w literaturze branżowej.',
  },
  {
    ruleId: 'PL-LEGAL-A-03a',
    category: 'A',
    description:
      'Maksymalna liczba stopni w jednym biegu schodów wewnętrznych (budynki ogólne, poza opieką zdrowotną). Nie dotyczy budynków jednorodzinnych, zagrodowych, rekreacji indywidualnej ani mieszkań dwupoziomowych.',
    condition: 'stepsPerFlight <= 17',
    configRefs: ['numTreads'],
    scope: { locations: ['internal'], buildingTypes: ['multi_family', 'public', 'preschool'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 69 ust. 1',
    severity: 'ERROR',
    blocksGeneration: true,
    notes:
      'Ten próg celowo NIE obejmuje buildingType "single_family" w scope — dla budynków jednorodzinnych przepis wprost nie ma zastosowania, więc profil POLAND_RESIDENTIAL_TIMBER (kontekst single_family) go pomija, a nie "łamie".',
  },
  {
    ruleId: 'PL-LEGAL-A-03b',
    category: 'A',
    description: 'Maksymalna liczba stopni w jednym biegu schodów wewnętrznych w budynkach opieki zdrowotnej.',
    condition: 'stepsPerFlight <= 14',
    configRefs: ['numTreads'],
    scope: { locations: ['internal'], buildingTypes: ['healthcare'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 69 ust. 1',
    severity: 'ERROR',
    blocksGeneration: true,
  },
  {
    ruleId: 'PL-LEGAL-A-04',
    category: 'A',
    description: 'Maksymalna liczba stopni w jednym biegu schodów zewnętrznych.',
    condition: 'stepsPerFlight <= 10',
    configRefs: ['numTreads'],
    scope: { locations: ['external'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 69 ust. 2',
    severity: 'ERROR',
    blocksGeneration: true,
  },
  {
    ruleId: 'PL-LEGAL-A-05a',
    category: 'A',
    description: 'Minimalna szerokość użytkowa biegu i maksymalna wysokość stopnia — budynki jednorodzinne, zagrodowe, mieszkania dwupoziomowe.',
    condition: 'stairWidth >= 0.8 m ; riserHeight <= 0.19 m',
    configRefs: ['stairWidth', 'riserHeight'],
    scope: { locations: ['internal'], buildingTypes: ['single_family'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 68 (tabela, wiersz: budynki jednorodzinne)',
    severity: 'ERROR',
    blocksGeneration: true,
    notes: 'To jest właściwy, atomowy wiersz tabeli dla profilu POLAND_RESIDENTIAL_TIMBER — patrz src/rules/profiles/.',
  },
  {
    ruleId: 'PL-LEGAL-A-05b',
    category: 'A',
    description: 'Minimalna szerokość użytkowa biegu i maksymalna wysokość stopnia — budynki wielorodzinne, użyteczności publicznej (poza ZOZ).',
    condition: 'stairWidth >= 1.2 m ; riserHeight <= 0.175 m',
    configRefs: ['stairWidth', 'riserHeight'],
    scope: { locations: ['internal'], buildingTypes: ['multi_family', 'public'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 68 (tabela)',
    severity: 'ERROR',
    blocksGeneration: true,
  },
  {
    ruleId: 'PL-LEGAL-A-05c',
    category: 'A',
    description: 'Minimalna szerokość użytkowa biegu i maksymalna wysokość stopnia — przedszkola/żłobki.',
    condition: 'stairWidth >= 1.2 m ; riserHeight <= 0.15 m',
    configRefs: ['stairWidth', 'riserHeight'],
    scope: { locations: ['internal'], buildingTypes: ['preschool'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 68 (tabela)',
    severity: 'ERROR',
    blocksGeneration: true,
  },
  {
    ruleId: 'PL-LEGAL-A-05d',
    category: 'A',
    description: 'Minimalna szerokość użytkowa biegu i maksymalna wysokość stopnia — zakłady opieki zdrowotnej.',
    condition: 'stairWidth >= 1.4 m ; riserHeight <= 0.15 m',
    configRefs: ['stairWidth', 'riserHeight'],
    scope: { locations: ['internal'], buildingTypes: ['healthcare'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 68 (tabela)',
    severity: 'ERROR',
    blocksGeneration: true,
  },
  {
    ruleId: 'PL-LEGAL-A-05e',
    category: 'A',
    description: 'Minimalna szerokość użytkowa biegu i maksymalna wysokość stopnia — piwnice/pomieszczenia techniczne, dowolny typ budynku.',
    condition: 'stairWidth >= 0.8 m ; riserHeight <= 0.20 m',
    configRefs: ['stairWidth', 'riserHeight'],
    scope: { locations: ['internal'], buildingTypes: ['all'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 68 (tabela)',
    severity: 'ERROR',
    blocksGeneration: true,
    notes: 'Dotyczy WYŁĄCZNIE schodów piwnicznych/technicznych — nie schodów głównych. Profil musi rozróżniać "rolę biegu" (główny vs. piwniczny), pole obecnie nieistniejące w config.js — dopóki go nie ma, ta reguła nie powinna być włączana automatycznie do profilu schodów głównych.',
  },
  {
    ruleId: 'PL-LEGAL-A-06',
    category: 'A',
    description: 'Minimalna szerokość biegu schodów zewnętrznych.',
    condition: 'stairWidth >= 1.2 m',
    configRefs: ['stairWidth'],
    scope: { locations: ['external'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 68',
    severity: 'ERROR',
    blocksGeneration: true,
  },
  {
    ruleId: 'PL-LEGAL-C-01',
    category: 'C',
    description:
      'Schody kręcone/zabiegowe: minimalna szerokość stopnia mierzona w odległości 0,4 m od słupa/osi wewnętrznej (duszy) wynosi 0,25 m.',
    condition: 'treadWidthAt(0.4 m from inner edge) >= 0.25 m',
    configRefs: ['walklineOffset', 'minInnerWidth'],
    scope: { locations: ['internal'], buildingTypes: ['all'] },
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 69 ust. 5 (schody kręcone i inne o zabiegowych stopniach)',
    severity: 'ERROR',
    blocksGeneration: true,
    notes:
      'UWAGA: obecny config.walklineOffset (400mm) i config.minInnerWidth (110mm) w schema.js NIE odzwierciedlają tego przepisu — przepis wymaga min. 250mm mierzone dokładnie 400mm od duszy, a nie dowolnego minInnerWidth. To rozbieżność do naprawienia przy budowie silnika walidacji, nie tylko dokumentacja.',
  },
  {
    ruleId: 'PL-LEGAL-D-01',
    category: 'D',
    description: 'Minimalna wysokość (skrajnia) nad spocznikiem/biegiem schodów, w świetle, mierzona pionowo.',
    condition: 'headroom >= 2.05 m',
    configRefs: ['minHeadroom', 'ceilingThickness'],
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source:
      'Rozporządzenie MI ws. warunków technicznych budynków — wartość 2,05 m potwierdzona wyłącznie przez wtórne źródła branżowe (prawo.pl), NIE zweryfikowana bezpośrednio w tekście paragrafu podczas tego badania.',
    severity: 'WARNING',
    blocksGeneration: false,
    needsVerification: true,
    notes:
      'config.minHeadroom w schema.js domyślnie ustawione na 2000mm (2,0 m) — jeśli prawidłowa wartość PL to 2,05 m, domyślna wartość aplikacji jest zaniżona. WYMAGA potwierdzenia w oryginalnym tekście rozporządzenia (prawdopodobnie inny paragraf niż § 66-71) przed podniesieniem do severity ERROR / blokady generacji.',
  },
  {
    ruleId: 'PL-LEGAL-H-01',
    category: 'H',
    description: 'Wysokość balustrady przy schodach i jej maksymalne prześwity w wypełnieniu.',
    condition: 'balustradeHeight >= 1.1 m; opening in filling <= 0.2 m (ogólnie) | <= 0.12 m (wielorodzinne, zbiorowego zamieszkania, oświata, ZOZ)',
    configRefs: [],
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'Rozporządzenie MI ws. warunków technicznych budynków, § 298',
    severity: 'ERROR',
    blocksGeneration: true,
    notes: 'Aplikacja obecnie NIE modeluje balustrady/poręczy w ogóle (brak w config.js) — ten obszar jest całkowicie poza dzisiejszym modelem geometrii.',
  },
  {
    ruleId: 'PL-LEGAL-I-01',
    category: 'I',
    description:
      'Obciążenie użytkowe schodów wg polskiego załącznika krajowego do PN-EN 1991-1-1 (kategoria A — schody w budynkach mieszkalnych) — wartość liczbowa NIE potwierdzona jednoznacznie w tym badaniu.',
    condition: 'imposedLoad(stairs) — patrz notes',
    configRefs: [],
    ruleType: 'LEGAL_REQUIREMENT',
    jurisdiction: 'PL',
    source: 'PN-EN 1991-1-1:2004 + polski Załącznik Krajowy, Tablica 6.2 (kategoria A) — WYMAGA weryfikacji w aktualnej normie/załączniku',
    severity: 'WARNING',
    blocksGeneration: false,
    needsVerification: true,
    notes:
      'Wyszukiwanie wskazało zakres 2,0-4,0 kN/m² dla stropów/balkonów/schodów kategorii A w ogólnej tabeli Eurokodu, ale polski załącznik krajowy nie został zweryfikowany źródłowo (napotkane źródła określiły go jako "wyjątkowo ubogi", tzn. może odsyłać do wartości zalecanej wprost). Dla porównania: brytyjski Załącznik Krajowy podaje 1,5 kN/m² UDL / 2,0 kN skupione dla kategorii A1 (patrz UK-GUID-I-01). NIE należy zakładać identycznej wartości dla Polski bez potwierdzenia.',
  },
]);
