// STRINGER CONSTRUCTION ASSUMPTIONS — the outcome of the "technical specification lock" stage
// (see docs/STRINGER_CONSTRUCTION_SPEC.md for the full narrative this data summarizes). Every
// entry here is a claim made by src/geometry/stringerConstructionGeometry.js or
// src/config/schema.js's stringer* fields, classified honestly: which are checked against a
// real source (CONFIRMED), which are Stair3D's own judgment call with no directly-supporting
// source (ASSUMPTION), and which are deliberately left to the user/company to set
// (CONFIGURABLE) — see RULE_STATUS in ../schema.js. Mixed ruleType values are intentional here
// (unlike the single-authority rule sets elsewhere in src/rules/sets/): this file's whole
// purpose is to hold a mixed set of claims about ONE subsystem, each honestly labeled.

import { defineRuleSet } from '../schema.js';

export const stringerConstructionAssumptions = defineRuleSet([
  {
    ruleId: 'STAIR3D-STRINGER-CUT-BOTTOM-PARALLEL',
    category: 'F',
    description: 'For a cut/open string, the lower edge is a single straight line parallel to the stair\'s pitch, independent of where the tread notches sit above it — never a stepped/sawtooth edge.',
    condition: 'outerContour bottom edge slope === pitchLine.slope, for the whole segment',
    configRefs: [],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'GENERAL',
    source: 'This Old House, "What to Know About Cutting Stair Stringers" (thisoldhouse.com/stairs/21591423); WOOD DESIGNER, "How to cut stair stringers: a complete guide" (wooddesigner.org) — both independently state the notched top / straight-parallel-bottom split for a cut string.',
    severity: 'INFO',
    blocksGeneration: false,
    status: 'CONFIRMED',
    constructionType: 'cut',
    affectsGeometry: true,
    affectsValidation: false,
    affectsMaterialTakeoff: true,
    notes: 'This is the GENERAL PRINCIPLE (straight-and-parallel bottom edge). It does NOT confirm the specific two-point-chord PROCEDURE stringerConstructionGeometry.js uses to compute that line — see STAIR3D-STRINGER-PITCH-LINE-METHOD below for that distinct claim.',
  },
  {
    ruleId: 'STAIR3D-STRINGER-PITCH-LINE-METHOD',
    category: 'F',
    description:
      'The stringer "pitch line" (the straight reference that both the cut-string bottom edge and the closed-string plain-rectangle contour are derived from) is computed as a straight chord through ONLY the first and last tread-bearing corner points of a segment.',
    condition: 'pitchLine = line(firstBearing.corner, lastBearing.corner)',
    configRefs: [],
    ruleType: 'SOFTWARE_DESIGN_CHOICE',
    jurisdiction: 'COMPANY',
    source: 'No published source found describing this exact two-point derivation as a general stringer-layout method; the published principle found (see STAIR3D-STRINGER-CUT-BOTTOM-PARALLEL) only establishes THAT the edge is straight/parallel, not HOW to compute it from bearing data.',
    severity: 'WARNING',
    blocksGeneration: false,
    needsVerification: true,
    status: 'ASSUMPTION',
    constructionType: 'both',
    affectsGeometry: true,
    affectsValidation: true,
    affectsMaterialTakeoff: true,
    notes:
      'Mathematically EXACT for a straight, uniform flight (bearingElevation is an exact affine function of tread index — see stringerSolver.js — so every bearing corner is already collinear; the two-point chord equals every other point exactly). Becomes an APPROXIMATION for: (a) winders, where going varies tread-to-tread within one segment, and (b) a heavily/asymmetrically manually-edited flight. `minRemainingSectionMm` is the safeguard that catches when the approximation degrades too far (see docs/STRINGER_CONSTRUCTION_SPEC.md §F). RECOMMENDATION: acceptable as the DEFAULT for straight and typical winder flights (verified clean across the reality-check scenarios); for a future stage, consider an explicit user-settable pitch angle / reference line as an alternative for atypical winders, rather than only the two-point chord — but do not implement this yet.',
  },
  {
    ruleId: 'STAIR3D-STRINGER-WINDER-SEGMENTED',
    category: 'F',
    description: 'A winder stringer is built as multiple independent straight boards (one per straight reference-line run), joined at each turn by a corner post (or a lap-joint overlap when no post) — never one continuously-curved board.',
    condition: 'segments.length > 1 for any flight containing a turn; each segment independently straight',
    configRefs: ['hasCornerPost'],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'GENERAL',
    source:
      'StairBox, "How to Fit Kite Winder Turns" (stairbox.com/staircase-fitting-guide-winders.html) — describes stringers around a winder/newel turn as modified/joined pieces meeting at the newel, glued/wedged or bolted, not a single curved member; consistent with BWF-GUID-F-03 already in bwfIndustryGuidance.js ("upper and lower strings at a winder turn may need local enlargement... a distinct, purpose-shaped construction problem").',
    severity: 'INFO',
    blocksGeneration: false,
    status: 'CONFIRMED',
    constructionType: 'both',
    affectsGeometry: true,
    affectsValidation: false,
    affectsMaterialTakeoff: true,
    notes:
      'CONFIRMED as the right STRUCTURAL CONCEPT (multi-piece, post-jointed). NOT yet implemented: BWF-GUID-F-03\'s "local enlargement... to accommodate the housings of the winder treads" (the board may need to be locally WIDER at a winder, not just longer) and the "curved triangle" transition piece some sources describe at the newel joint (StairBox) — the current model terminates each segment as a plain flat end at the post, with no shaped transition piece. Both are documented simplifications, not implemented in this stage.',
  },
  {
    ruleId: 'STAIR3D-STRINGER-TOP-MARGIN-DEFAULT',
    category: 'F',
    description: 'Default value for how far a closed/housed stringer\'s top edge extends above the pitch line (config.stringerTopMarginMm = 50mm).',
    condition: 'stringerTopMarginMm = 50 (default; user/company adjustable)',
    configRefs: ['stringerTopMarginMm'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No authoritative universal value found; this is a Stair3D default, not a cited figure.',
    severity: 'INFO',
    blocksGeneration: false,
    status: 'CONFIGURABLE',
    constructionType: 'closed',
    affectsGeometry: true,
    affectsValidation: false,
    affectsMaterialTakeoff: true,
    notes: 'Do not present this default as "recommended" in any UI copy — it is an unvalidated starting point only.',
  },
  {
    ruleId: 'STAIR3D-STRINGER-MIN-DEPTH-DEFAULT',
    category: 'F',
    description: 'Default minimum LOCAL STRINGER DEPTH (config.minimumStringerDepthMm = 350mm): the minimum geometric distance between the structural reference curve R (through the tread front corners) and the lower contour L, measured in the profile — not a vertical Z difference and not a bounding-box size. Locally the depth may be larger (360/390/450mm), never smaller. It is also the distance the AUTO lower contour is generated at (plus config.stringerProfileOffsetMm).',
    condition: 'minimumStringerDepthMm = 350 (default; user/company adjustable); violation -> STRINGER-MIN-DEPTH ERROR',
    configRefs: ['minimumStringerDepthMm', 'stringerProfileOffsetMm'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No authoritative universal value; the 350mm figure is a Stair3D/company working default (see docs/architecture/STRINGER_PROFILE_MODEL.md).',
    severity: 'INFO',
    blocksGeneration: false,
    status: 'CONFIGURABLE',
    constructionType: 'both',
    affectsGeometry: true,
    affectsValidation: true,
    affectsMaterialTakeoff: true,
    notes: 'Not the board THICKNESS (config.stringerThickness) and not the blank (raw board) depth — the blank must also cover the stepped comb and any deeper local profile, and will be derived from the solved profile in a later stage; today the takeoff still reads the nominal depth.',
  },
  {
    ruleId: 'STAIR3D-STRINGER-MIN-SECTION-DEFAULT',
    category: 'F',
    description: 'Default diagnostic threshold for the minimum acceptable remaining board material at the thinnest point (config.stringerMinRemainingSectionMm = 30mm).',
    condition: 'stringerMinRemainingSectionMm = 30 (default; user/company adjustable)',
    configRefs: ['stringerMinRemainingSectionMm'],
    ruleType: 'MANUFACTURING_ASSUMPTION',
    jurisdiction: 'COMPANY',
    source: 'No structural calculation or code backs this number; it is a Stair3D sanity-check default.',
    severity: 'INFO',
    blocksGeneration: false,
    status: 'CONFIGURABLE',
    constructionType: 'both',
    affectsGeometry: false,
    affectsValidation: true,
    affectsMaterialTakeoff: false,
    notes: 'A real structural minimum would require a species/grade-specific bending/shear check (Eurocode 5), not a flat mm figure — out of scope for this stage; see EC5-STRUCT-* entries in eurocodeStructural.js for the structural-calculation layer this should eventually connect to.',
  },
  {
    ruleId: 'STAIR3D-STRINGER-HOUSING-DEPTH-FORMULA',
    category: 'F',
    description: 'Closed/housed stringer housing depth = max(12mm, 0.4 x stringerThickness) — same formula as BWF-GUID-F-01, reused via stringerModel.js housingDepthFor().',
    condition: 'housingDepth = max(12mm, 0.4 * stringerThickness)',
    configRefs: ['stringerThickness'],
    ruleType: 'INDUSTRY_BEST_PRACTICE',
    jurisdiction: 'UK',
    source: 'BWF Timber Stair Design Guide 2013 §6.2.3 (same citation as BWF-GUID-F-01 in bwfIndustryGuidance.js — not re-verified independently in this stage, carried forward as previously cited).',
    severity: 'INFO',
    blocksGeneration: false,
    status: 'CONFIRMED',
    constructionType: 'closed',
    affectsGeometry: true,
    affectsValidation: true,
    affectsMaterialTakeoff: true,
    notes:
      'MEANING CURRENTLY CONFLATED (flagged, not fixed in this stage): this ONE number is used simultaneously as (a) the visual recess depth rendered in 3D, (b) the input to the minRemainingSectionMm structural diagnostic, and (c) what a future manufacturing drawing would presumably read as the actual routing depth. BWF-GUID-F-01\'s own wording describes a MINIMUM depth requirement, not necessarily the exact depth a real housing is routed to (real housed joints are additionally TAPERED/wedged — see STAIR3D-HOUSING-RECTANGULAR-SIMPLIFICATION). RECOMMENDATION: before Material Takeoff depends on this number for real material quantities, separate "structural minimum" (this formula) from "actual routing depth" (may be deeper, a manufacturing choice) explicitly.',
  },
  {
    ruleId: 'STAIR3D-HOUSING-RECTANGULAR-SIMPLIFICATION',
    category: 'F',
    description: 'Housed-stringer housings are modeled as plain rectangular recesses. Real housed joints are typically TAPERED (back-angled) mortises, glued and driven with a matching wedge for a tight, self-locking fit.',
    condition: 'n/a — geometric simplification, not a numeric rule',
    configRefs: [],
    ruleType: 'ENGINEERING_GUIDANCE',
    jurisdiction: 'GENERAL',
    source:
      'Fine Homebuilding, "Shop-Built Housed-Stringer Stairs" and "How To Build Housed-Stringer Stairs" (finehomebuilding.com) — "the backsides of these mortises taper, and wedges that match the taper are glued and driven in to lock the stairs into a cohesive unit."',
    severity: 'INFO',
    blocksGeneration: false,
    status: 'CONFIRMED',
    constructionType: 'closed',
    affectsGeometry: true,
    affectsValidation: false,
    affectsMaterialTakeoff: false,
    notes:
      'The CURRENT 3D model may remain a plain rectangle for now (explicitly acceptable per this stage\'s scope), but the DATA MODEL (StringerHousing typedef) should remain capable of adding a taper angle / wedge component later without a breaking change — i.e., do not assume the housing is forever a simple axis-aligned box when extending this later. affectsMaterialTakeoff is false FOR NOW (no wedge/glue line items exist yet) but will become true once a takeoff models fasteners/wedges.',
  },
]);
